# Generated by Django 3.0.4 on 2020-03-14 19:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('tablica', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='tresc',
        ),
    ]
